export const resObj = [
  {
    id: 1,
    resName: "KFC",
    cuisine: "Burger,Asian",
    avgRating: "3.8",
    dilveryTime: "48 mins",
  },
  {
    id: 2,
    resName: "Mcdonalds",
    cuisine: "Burger,Asian,Pizza",
    avgRating: "3.8",
    dilveryTime: "48 mins",
  },
  {
    id: 3,
    resName: "Ice Cube",
    cuisine: "Burger,North Indian",
    avgRating: "3.8",
    dilveryTime: "48 mins",
  },
  {
    id: 4,
    resName: "ABC",
    cuisine: "Burger,Asian",
    avgRating: "2.8",
    dilveryTime: "48 mins",
  },
  {
    id: 5,
    resName: "CDE",
    cuisine: "Burger,Asian",
    avgRating: "4.8",
    dilveryTime: "48 mins",
  },
  {
    id: 6,
    resName: "Haveli",
    cuisine: "Burger,Asian",
    avgRating: "3.0",
    dilveryTime: "48 mins",
  },
  {
    id: 7,
    resName: "Vikas Bhojanalaya",
    cuisine: "Burger,Asian",
    avgRating: "4.5",
    dilveryTime: "48 mins",
  },
  {
    id: 8,
    resName: "QWE",
    cuisine: "Burger,Asian",
    avgRating: "4.8",
    dilveryTime: "48 mins",
  },
  {
    id: 9,
    resName: "ASD",
    cuisine: "Burger,Asian",
    avgRating: "4.2",
    dilveryTime: "48 mins",
  },
];
